export declare type EventType = "doors-changed" 
                              | "instruments-changed" 
                              | "location-changed" 
                              | "deviceid-changed"
                              | "device-added"
                              | "device-deleted"